# -*- coding: utf-8 -*-
"""CodeForPlotGeneration.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19sG4ezvHFOus2WjaqKbUuHkGLn6QOM-g
"""

import sqlite3
import matplotlib.pyplot as plt

# Connect to the SQLite3 database
conn = sqlite3.connect('my_database.db')

# Execute the SQL procedure to retrieve the data
cur = conn.cursor()
cur.execute('CALL my_proc()')
data = cur.fetchall()
cur.close()

# Separate the x and y values into two lists
x_values = [row[0] for row in data]
y_values = [row[1] for row in data]

# Generate the chart using Matplotlib
plt.plot(x_values, y_values)
plt.title('My Chart')
plt.xlabel('X Axis')
plt.ylabel('Y Axis')
plt.savefig('my_chart.png')
plt.show()

# Close the database connection
conn.close()